# -*- coding: utf-8 -*-
"""SHOPPING_TRENDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4QvOmHydHW4PACGZeIKaQl8g4tHZpHD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
file_path = "/content/shopping_trends_dataset 1.csv"
df = pd.read_csv(file_path)

# Display basic info
def data_overview():
    print("Dataset Overview:")
    print(df.info())
    print("\nMissing Values:")
    print(df.isnull().sum())
    print("\nBasic Statistics:")
    print(df.describe())

data_overview()

# Data Cleaning: Drop duplicates and fill missing values
df.drop_duplicates(inplace=True)
df.fillna(df.mode().iloc[0], inplace=True)

# Exploratory Data Analysis (EDA)
def purchase_trends():
    plt.figure(figsize=(10,5))
    sns.histplot(df['Purchase Amount (USD)'], bins=30, kde=True, color='skyblue')
    plt.title('Distribution of Purchase Amounts')
    plt.xlabel('Purchase Amount (USD)')
    plt.ylabel('Frequency')
    plt.show()

    plt.figure(figsize=(10,5))
    sns.countplot(data=df, x='Category', order=df['Category'].value_counts().index, palette='viridis')
    plt.title('Popular Shopping Categories')
    plt.xlabel('Category')
    plt.ylabel('Count')
    plt.xticks(rotation=45)
    plt.show()

    plt.figure(figsize=(10,5))
    sns.countplot(data=df, x='Gender', hue='Category', palette='pastel')
    plt.title('Shopping Trends by Gender')
    plt.xlabel('Gender')
    plt.ylabel('Count')
    plt.show()

purchase_trends()

# Trends based on Season
def season_trends():
    plt.figure(figsize=(10,5))
    sns.countplot(data=df, x='Season', hue='Category', palette='coolwarm')
    plt.title('Shopping Trends Across Seasons')
    plt.xlabel('Season')
    plt.ylabel('Count')
    plt.show()

season_trends()

# Payment method preferences
def payment_trends():
    # Check for column name variations and correct if necessary
    payment_column = 'Preferred Payment Method'
    if payment_column not in df.columns:
        # Try variations like "preferred_payment_method", "payment_method", etc.
        for col in df.columns:
            if 'payment' in col.lower():
                payment_column = col
                print(f"Column name corrected to: {payment_column}")
                break
        else:
            raise KeyError(f"No column related to 'payment' found in the DataFrame.")

    plt.figure(figsize=(10,5))
    sns.countplot(data=df, y=payment_column, order=df[payment_column].value_counts().index, palette='muted')
    plt.title('Preferred Payment Methods')
    plt.xlabel('Count')
    plt.ylabel('Payment Method')
    plt.show()

payment_trends()

print("Analysis Completed!")